name: CollectionViewLayouts
markdown: redcarpet
highlighter: pygments
permalink: /:title/
url: http://sdgandhi.github.io/CollectionViewLayouts/
author:
    name: Sidhant Gandhi
    twitter: sidhantgandhi
