name: CollectionViewLayouts
markdown: kramdown
highlighter: rouge
permalink: /:title/
url: http://sdgandhi.github.io/CollectionViewLayouts/
author:
    name: Sidhant Gandhi
    twitter: sidhantgandhi
